blueprint:
  name: Sunricher ZGRC-KEY-013 (Version Action V5)
  description: Gestion On/Off et Variation fluide via Zigbee2MQTT
  domain: automation

  input:
    action_sensor:
      name: Capteur Action
      description: Le sensor qui remonte on_1, move_up_1, etc.
      selector:
        entity:
          domain: sensor
          multiple: false

    light_g1:
      name: Groupe 1
      selector:
        entity:
          domain: light
    light_g2:
      name: Groupe 2
      selector:
        entity:
          domain: light
    light_g3:
      name: Groupe 3
      selector:
        entity:
          domain: light
    light_g4:
      name: Groupe 4
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  # On recupere l'etat du sensor et on l'appelle 'action' pour coller a vos logs
  - variables:
      action: "{{ trigger.to_state.state }}"
      sensor: !input action_sensor

  - choose:
      # =========================================
      # GROUPE 1
      # =========================================
      - conditions: "{{ action == 'on_1' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g1 }

      - conditions: "{{ action == 'off_1' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g1 }

      # Variation Monter
      - conditions: "{{ action == 'brightness_move_up_1' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_up_1') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g1 }
                  data: { brightness_step_pct: 5, transition: 0.1 }
                - delay: 0.1

      # Variation Descendre
      - conditions: "{{ action == 'brightness_move_down_1' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_down_1') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g1 }
                  data: { brightness_step_pct: -5, transition: 0.1 }
                - delay: 0.1

      # =========================================
      # GROUPE 2
      # =========================================
      - conditions: "{{ action == 'on_2' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g2 }

      - conditions: "{{ action == 'off_2' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g2 }

      - conditions: "{{ action == 'brightness_move_up_2' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_up_2') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g2 }
                  data: { brightness_step_pct: 5, transition: 0.1 }
                - delay: 0.1

      - conditions: "{{ action == 'brightness_move_down_2' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_down_2') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g2 }
                  data: { brightness_step_pct: -5, transition: 0.1 }
                - delay: 0.1

      # =========================================
      # GROUPE 3
      # =========================================
      - conditions: "{{ action == 'on_3' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g3 }

      - conditions: "{{ action == 'off_3' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g3 }

      - conditions: "{{ action == 'brightness_move_up_3' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_up_3') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g3 }
                  data: { brightness_step_pct: 5, transition: 0.1 }
                - delay: 0.1

      - conditions: "{{ action == 'brightness_move_down_3' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_down_3') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g3 }
                  data: { brightness_step_pct: -5, transition: 0.1 }
                - delay: 0.1

      # =========================================
      # GROUPE 4
      # =========================================
      - conditions: "{{ action == 'on_4' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g4 }

      - conditions: "{{ action == 'off_4' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g4 }

      - conditions: "{{ action == 'brightness_move_up_4' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_up_4') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g4 }
                  data: { brightness_step_pct: 5, transition: 0.1 }
                - delay: 0.1

      - conditions: "{{ action == 'brightness_move_down_4' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ is_state(sensor, 'brightness_move_down_4') }}"
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g4 }
                  data: { brightness_step_pct: -5, transition: 0.1 }
                - delay: 0.1