blueprint:
  name: AwoX 33952 - Direct (V5 - Force & Effets)
  description: "V5 : Pas de température plus grand, effet Colorloop forcé et codes Cœurs standards."
  domain: automation

  input:
    action_sensor:
      name: Capteur Action (Z2M)
      selector:
        entity:
          domain: sensor
          multiple: false

    target_light:
      name: Lampe / Groupe à piloter
      selector:
        entity:
          domain: light

    # --- Actions Cœurs ---
    heart_1_action:
      name: Action Cœur 1 (Haut)
      description: "Si le code est 'recall_1' ou 'scene_1'"
      default: []
      selector:
        action: {}

    heart_2_action:
      name: Action Cœur 2 (Bas)
      description: "Si le code est 'recall_2' ou 'scene_2'"
      default: []
      selector:
        action: {}

    # --- Réglages ---
    step_pct:
      name: Pas de Luminosité (%)
      default: 15
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"
          mode: slider

    kelvin_step:
      name: Pas de Température (Mireds)
      description: "Augmentez ce chiffre (ex: 80) si le changement de blanc est invisible."
      default: 80
      selector:
        number:
          min: 10
          max: 200
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
      light_entity: !input target_light
      step_p: !input step_pct
      step_k: !input kelvin_step
      
      # Calculs
      step_up: "{{ step_p | int }}"
      step_down: "{{ -1 * step_p | int }}"
      
      # Mireds : 
      # UP (Augmenter Mireds) = Vers le JAUNE/CHAUD
      # DOWN (Baisser Mireds) = Vers le BLEU/FROID
      mireds_warmer: "{{ step_k | int }}"
      mireds_colder: "{{ -1 * step_k | int }}"

  - choose:
      # =========================================
      # 1. I/O (ON / OFF)
      # =========================================
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input target_light }

      # =========================================
      # 2. LUMINOSITÉ (Soleils)
      # =========================================
      - conditions: "{{ action == 'brightness_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { brightness_step_pct: "{{ step_up }}", transition: 0.2 }

      - conditions: "{{ action == 'brightness_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { brightness_step_pct: "{{ step_down }}", transition: 0.2 }

      # =========================================
      # 3. TEMPÉRATURE (Etoile/Flocon)
      # =========================================
      # NOTE : Si les boutons sont inversés, inversez mireds_warmer et colder ici
      
      # Step UP (Souvent Soleil) -> On chauffe
      - conditions: "{{ action == 'color_temperature_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { color_temp_step: "{{ mireds_warmer }}", transition: 0.2 }

      # Step DOWN (Souvent Flocon) -> On refroidit
      - conditions: "{{ action == 'color_temperature_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { color_temp_step: "{{ mireds_colder }}", transition: 0.2 }

      # =========================================
      # 4. MODES (Flèches centrales)
      # =========================================
      # HAUT (Refresh) -> Reset Blanc Neutre
      - conditions: "{{ action == 'refresh' }}" 
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { kelvin: 4000, brightness_pct: 100, effect: "None" }

      # BAS (Light Movement) -> FORCE COLOR LOOP
      - conditions: "{{ action == 'light_movement' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: 
              effect: "colorloop"
              brightness_pct: 100

      # =========================================
      # 5. COULEURS (Disque)
      # =========================================
      - conditions: "{{ action == 'red' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [255, 0, 0], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'green' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [0, 255, 0], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'blue' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [0, 0, 255], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'yellow' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [255, 220, 0], brightness_pct: 100, effect: "stop" }

      # =========================================
      # 6. FAVORIS (Cœurs) - Essai de codes
      # =========================================
      # Regarde dans le journal si ces codes apparaissent quand tu cliques
      - conditions: "{{ action in ['recall_1', 'store_1', 'scene_1'] }}"
        sequence: !input heart_1_action

      - conditions: "{{ action in ['recall_2', 'store_2', 'scene_2'] }}"
        sequence: !input heart_2_action