blueprint:
  name: Sunricher ZGRC-KEY-013 (Turbo Fluide V8)
  description: Variation ultra-fluide (petits pas rapides). Réglez la vitesse via le délai inter-commande.
  domain: automation

  input:
    action_sensor:
      name: Capteur Action
      description: Le sensor qui remonte on_1, move_up_1, etc.
      selector:
        entity:
          domain: sensor
          multiple: false

    loop_delay:
      name: Délai entre les commandes (Vitesse)
      description: "Plus ce chiffre est PETIT, plus la variation est RAPIDE. (Conseillé: 50ms à 100ms)"
      default: 100
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: "ms"
          mode: slider

    light_g1:
      name: Groupe 1
      selector:
        entity:
          domain: light
    light_g2:
      name: Groupe 2
      selector:
        entity:
          domain: light
    light_g3:
      name: Groupe 3
      selector:
        entity:
          domain: light
    light_g4:
      name: Groupe 4
      selector:
        entity:
          domain: light

# Mode Restart obligatoire pour couper la boucle instantanément
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
      # On convertit les ms en secondes pour le délai (ex: 100ms = 0.1s)
      delay_ms: !input loop_delay
      delay_sec: "{{ delay_ms / 1000 }}"
      # Pas fixe de 4% pour garantir la fluidité visuelle
      step_up: 4
      step_down: -4

  - choose:
      # =========================================
      # GROUPE 1
      # =========================================
      - conditions: "{{ action == 'on_1' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g1 }

      - conditions: "{{ action == 'off_1' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g1 }

      # Variation Monter G1
      - conditions: "{{ action == 'brightness_move_up_1' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g1 }
                  # Transition égale au délai pour lisser parfaitement
                  data: { brightness_step_pct: "{{ step_up }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      # Variation Descendre G1
      - conditions: "{{ action == 'brightness_move_down_1' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g1 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      # =========================================
      # GROUPE 2
      # =========================================
      - conditions: "{{ action == 'on_2' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g2 }

      - conditions: "{{ action == 'off_2' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g2 }

      - conditions: "{{ action == 'brightness_move_up_2' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g2 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      - conditions: "{{ action == 'brightness_move_down_2' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g2 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      # =========================================
      # GROUPE 3
      # =========================================
      - conditions: "{{ action == 'on_3' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g3 }

      - conditions: "{{ action == 'off_3' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g3 }

      - conditions: "{{ action == 'brightness_move_up_3' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g3 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      - conditions: "{{ action == 'brightness_move_down_3' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g3 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      # =========================================
      # GROUPE 4
      # =========================================
      - conditions: "{{ action == 'on_4' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g4 }

      - conditions: "{{ action == 'off_4' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g4 }

      - conditions: "{{ action == 'brightness_move_up_4' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g4 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"

      - conditions: "{{ action == 'brightness_move_down_4' }}"
        sequence:
          - repeat:
              count: 200
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g4 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: "{{ delay_sec }}" }
                - delay: "{{ delay_sec }}"