blueprint:
  name: AwoX 33952 - Direct (V4 - Simple & Rapide)
  description: "Version optimisée avec vos codes : 1 clic = 1 action immédiate."
  domain: automation

  input:
    action_sensor:
      name: Capteur Action (Z2M)
      description: "Le sensor qui remonte les clics."
      selector:
        entity:
          domain: sensor
          multiple: false

    target_light:
      name: Lampe / Groupe à piloter
      selector:
        entity:
          domain: light

    # --- Actions Cœurs (Si jamais tu trouves leurs codes plus tard) ---
    heart_1_action:
      name: Action Cœur 1 (Haut)
      description: "Action optionnelle."
      default: []
      selector:
        action: {}

    heart_2_action:
      name: Action Cœur 2 (Bas)
      description: "Action optionnelle."
      default: []
      selector:
        action: {}

    # --- Réglages ---
    step_pct:
      name: Pas de Luminosité (%)
      description: "Pourcentage ajouté/enlevé à chaque clic."
      default: 10
      selector:
        number:
          min: 5
          max: 30
          unit_of_measurement: "%"
          mode: slider

    kelvin_step:
      name: Pas de Température (Mireds)
      description: "Quantité de changement chaud/froid à chaque clic."
      default: 40
      selector:
        number:
          min: 10
          max: 100
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
      light_entity: !input target_light
      # Réglages
      step_p: !input step_pct
      step_k: !input kelvin_step
      # Calculs simples
      step_up: "{{ step_p | int }}"
      step_down: "{{ -1 * step_p | int }}"
      # Mireds : Plus le chiffre est grand, plus c'est chaud.
      # Donc "Step Up" (vers le froid/soleil) = réduire mireds
      # "Step Down" (vers le chaud) = augmenter mireds
      mireds_colder: "{{ -1 * step_k | int }}"
      mireds_warmer: "{{ step_k | int }}"

  - choose:
      # =========================================
      # 1. I/O (ON / OFF)
      # =========================================
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { transition: 0.5 }

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input target_light }
            data: { transition: 0.5 }

      # =========================================
      # 2. LUMINOSITÉ (Soleils)
      # =========================================
      - conditions: "{{ action == 'brightness_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { brightness_step_pct: "{{ step_up }}", transition: 0.2 }

      - conditions: "{{ action == 'brightness_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { brightness_step_pct: "{{ step_down }}", transition: 0.2 }

      # =========================================
      # 3. TEMPÉRATURE (Etoile/Flocon)
      # =========================================
      # Step UP = Souvent icone Soleil/Etoile (Froid)
      - conditions: "{{ action == 'color_temperature_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { color_temp_step: "{{ mireds_colder }}", transition: 0.2 }

      # Step DOWN = Souvent icone Chaud
      - conditions: "{{ action == 'color_temperature_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { color_temp_step: "{{ mireds_warmer }}", transition: 0.2 }

      # =========================================
      # 4. MODES (Flèches centrales)
      # =========================================
      # HAUT (Refresh) -> Reset Blanc Neutre
      - conditions: "{{ action == 'refresh' }}" 
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { kelvin: 4000, brightness_pct: 100, effect: "None" }

      # BAS (Light Movement) -> Color Loop
      - conditions: "{{ action == 'light_movement' }}"
        sequence:
           - choose:
              # Si effet déjà actif, on stop
              - conditions: "{{ state_attr(light_entity, 'effect') == 'colorloop' }}"
                sequence:
                  - service: light.turn_on
                    target: { entity_id: !input target_light }
                    data: { effect: "stop" }
              # Sinon on active
              - conditions: "{{ state_attr(light_entity, 'effect') != 'colorloop' }}"
                sequence:
                  - service: light.turn_on
                    target: { entity_id: !input target_light }
                    data: { effect: "colorloop", brightness_pct: 100 }

      # =========================================
      # 5. COULEURS (Disque)
      # =========================================
      - conditions: "{{ action == 'red' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [255, 0, 0], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'green' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [0, 255, 0], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'blue' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [0, 0, 255], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'yellow' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [255, 220, 0], brightness_pct: 100, effect: "stop" }

      # =========================================
      # 6. FAVORIS (Cœurs) - Codes supposés
      # =========================================
      # Si tu trouves les codes, remplace 'recall_1' ci-dessous
      - conditions: "{{ action in ['recall_1', 'store_1'] }}"
        sequence: !input heart_1_action

      - conditions: "{{ action in ['recall_2', 'store_2'] }}"
        sequence: !input heart_2_action