blueprint:
  name: AwoX 33952 - Spécial Yeelight (V10 - Rapide)
  description: "V10 : Transition rapide (0.1s), choix du nom de l'effet et suppression du toggle capricieux."
  domain: automation

  input:
    action_sensor:
      name: Capteur Action (Z2M)
      selector:
        entity:
          domain: sensor
          multiple: false

    target_light:
      name: Lampe Yeelight
      selector:
        entity:
          domain: light

    # --- Actions Cœurs ---
    heart_1_action:
      name: Action Cœur 1 (Haut)
      default: []
      selector:
        action: {}

    heart_2_action:
      name: Action Cœur 2 (Bas)
      default: []
      selector:
        action: {}

    # --- Réglages Effet ---
    effect_name:
      name: Nom de l'effet (Arc-en-ciel)
      description: "Nom exact de l'effet dans HA (ex: Slowdown, Disco, Color Loop...)."
      default: "Slowdown"
      selector:
        text: {}

    # --- Réglages Valeurs ---
    step_pct:
      name: Pas de Luminosité (%)
      default: 15
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"
          mode: slider

    kelvin_step:
      name: Pas de Température (Mireds)
      default: 50
      selector:
        number:
          min: 10
          max: 150
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
      light_entity: !input target_light
      step_p: !input step_pct
      step_k: !input kelvin_step
      effect_n: !input effect_name
      
      # 1. CALCULS LUMINOSITÉ
      current_bri: "{{ state_attr(light_entity, 'brightness') | int(default=0) }}"
      step_bri: "{{ (step_p / 100.0 * 255) | int }}"
      next_bri_up: "{{ [ (current_bri + step_bri), 255 ] | min }}"
      next_bri_down: "{{ [ (current_bri - step_bri), 5 ] | max }}"

      # 2. CALCULS TEMPÉRATURE
      current_mireds: "{{ state_attr(light_entity, 'color_temp') | int(default=370) }}"
      min_mireds: 153
      max_mireds: 500
      next_warm: "{{ [ (current_mireds + step_k), max_mireds ] | min }}"
      next_cold: "{{ [ (current_mireds - step_k), min_mireds ] | max }}"

  - choose:
      # =========================================
      # 1. I/O (ON / OFF)
      # =========================================
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input target_light }

      # =========================================
      # 2. LUMINOSITÉ (Transition 0.1s)
      # =========================================
      - conditions: "{{ action == 'brightness_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              brightness: "{{ next_bri_up }}"
              transition: 0.1

      - conditions: "{{ action == 'brightness_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              brightness: "{{ next_bri_down }}"
              transition: 0.1

      # =========================================
      # 3. TEMPÉRATURE (Transition 0.1s)
      # =========================================
      - conditions: "{{ action == 'color_temperature_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              color_temp: "{{ next_cold }}"
              transition: 0.1

      - conditions: "{{ action == 'color_temperature_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              color_temp: "{{ next_warm }}"
              transition: 0.1

      # =========================================
      # 4. MODES
      # =========================================
      # REFRESH -> Reset Blanc
      - conditions: "{{ action == 'refresh' }}" 
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              kelvin: 4000
              brightness_pct: 100
              effect: "None"

      # LIGHT MOVEMENT -> LANCE L'EFFET CHOISI
      - conditions: "{{ action == 'light_movement' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              effect: "{{ effect_n }}"
              brightness_pct: 100

      # =========================================
      # 5. COULEURS
      # =========================================
      - conditions: "{{ action == 'red' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              rgb_color: [255, 0, 0]
              brightness_pct: 100
              effect: "stop"

      - conditions: "{{ action == 'green' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              rgb_color: [0, 255, 0]
              brightness_pct: 100
              effect: "stop"

      - conditions: "{{ action == 'blue' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              rgb_color: [0, 0, 255]
              brightness_pct: 100
              effect: "stop"

      - conditions: "{{ action == 'yellow' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data:
              rgb_color: [255, 220, 0]
              brightness_pct: 100
              effect: "stop"

      # =========================================
      # 6. FAVORIS (Cœurs)
      # =========================================
      - conditions: "{{ action in ['recall_1', 'store_1', 'scene_1'] }}"
        sequence: !input heart_1_action

      - conditions: "{{ action in ['recall_2', 'store_2', 'scene_2'] }}"
        sequence: !input heart_2_action