blueprint:
  name: Sunricher ZGRC-KEY-013 (Vitesse Réglable V7)
  description: Gestion On/Off et Variation avec vitesse réglable via Zigbee2MQTT.
  domain: automation

  input:
    action_sensor:
      name: Capteur Action
      description: Le sensor qui remonte on_1, move_up_1, etc.
      selector:
        entity:
          domain: sensor
          multiple: false

    dimming_speed:
      name: Vitesse de variation
      description: Pourcentage de luminosité par pas (Plus le chiffre est haut, plus ça va vite).
      default: 5
      selector:
        number:
          min: 1
          max: 20
          unit_of_measurement: "%"
          mode: slider

    light_g1:
      name: Groupe 1
      selector:
        entity:
          domain: light
    light_g2:
      name: Groupe 2
      selector:
        entity:
          domain: light
    light_g3:
      name: Groupe 3
      selector:
        entity:
          domain: light
    light_g4:
      name: Groupe 4
      selector:
        entity:
          domain: light

# Le mode restart est OBLIGATOIRE. 
# C'est lui qui arrête la variation quand le sensor passe à "stop" ou "vide".
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
      speed: !input dimming_speed
      # On force la vitesse en nombre entier pour les calculs
      step_up: "{{ speed | int }}"
      step_down: "{{ -1 * speed | int }}"

  - choose:
      # =========================================
      # GROUPE 1
      # =========================================
      - conditions: "{{ action == 'on_1' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g1 }

      - conditions: "{{ action == 'off_1' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g1 }

      # Variation Monter G1
      - conditions: "{{ action == 'brightness_move_up_1' }}"
        sequence:
          - repeat:
              count: 150 # Permet de varier pendant ~15-20 secondes max sans relâcher
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g1 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: 0.1 }
                - delay: 0.1

      # Variation Descendre G1
      - conditions: "{{ action == 'brightness_move_down_1' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g1 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: 0.1 }
                - delay: 0.1

      # =========================================
      # GROUPE 2
      # =========================================
      - conditions: "{{ action == 'on_2' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g2 }

      - conditions: "{{ action == 'off_2' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g2 }

      # Variation Monter G2
      - conditions: "{{ action == 'brightness_move_up_2' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g2 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: 0.1 }
                - delay: 0.1

      # Variation Descendre G2
      - conditions: "{{ action == 'brightness_move_down_2' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g2 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: 0.1 }
                - delay: 0.1

      # =========================================
      # GROUPE 3
      # =========================================
      - conditions: "{{ action == 'on_3' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g3 }

      - conditions: "{{ action == 'off_3' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g3 }

      # Variation Monter G3
      - conditions: "{{ action == 'brightness_move_up_3' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g3 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: 0.1 }
                - delay: 0.1

      # Variation Descendre G3
      - conditions: "{{ action == 'brightness_move_down_3' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g3 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: 0.1 }
                - delay: 0.1

      # =========================================
      # GROUPE 4
      # =========================================
      - conditions: "{{ action == 'on_4' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input light_g4 }

      - conditions: "{{ action == 'off_4' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input light_g4 }

      # Variation Monter G4
      - conditions: "{{ action == 'brightness_move_up_4' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g4 }
                  data: { brightness_step_pct: "{{ step_up }}", transition: 0.1 }
                - delay: 0.1

      # Variation Descendre G4
      - conditions: "{{ action == 'brightness_move_down_4' }}"
        sequence:
          - repeat:
              count: 150
              sequence:
                - service: light.turn_on
                  target: { entity_id: !input light_g4 }
                  data: { brightness_step_pct: "{{ step_down }}", transition: 0.1 }
                - delay: 0.1