blueprint:
  name: Zigbee2MQTT ULTIMATE - Sunricher ZGRC-KEY-013 Native Dimming
  description: Native Zigbee dimming using brightness_move
  domain: automation

  input:
    remote_name:
      name: Zigbee2MQTT friendly name of remote
      selector:
        text:

    z2m_group1:
      name: Zigbee2MQTT group name G1
      selector:
        text:
    z2m_group2:
      name: Zigbee2MQTT group name G2
      selector:
        text:
    z2m_group3:
      name: Zigbee2MQTT group name G3
      selector:
        text:
    z2m_group4:
      name: Zigbee2MQTT group name G4
      selector:
        text:

mode: parallel
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action

variables:
  remote: !input remote_name
  action: "{{ trigger.payload }}"
  topic: "{{ trigger.topic }}"
  g1: !input z2m_group1
  g2: !input z2m_group2
  g3: !input z2m_group3
  g4: !input z2m_group4

condition:
  - "{{ topic == 'zigbee2mqtt/' ~ remote ~ '/action' }}"

action:
  - choose:

      ###################################################
      # GROUP 1 DIM UP
      ###################################################
      - conditions: "{{ action == 'group_1_on_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"brightness_move": 50}'

      - conditions: "{{ action == 'group_1_off_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"brightness_move": -50}'

      - conditions: "{{ action in ['group_1_on_release','group_1_off_release'] }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"brightness_move": 0}'

      ###################################################
      # GROUP 2
      ###################################################
      - conditions: "{{ action == 'group_2_on_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"brightness_move": 50}'

      - conditions: "{{ action == 'group_2_off_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"brightness_move": -50}'

      - conditions: "{{ action in ['group_2_on_release','group_2_off_release'] }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"brightness_move": 0}'

      ###################################################
      # GROUP 3
      ###################################################
      - conditions: "{{ action == 'group_3_on_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"brightness_move": 50}'

      - conditions: "{{ action == 'group_3_off_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"brightness_move": -50}'

      - conditions: "{{ action in ['group_3_on_release','group_3_off_release'] }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"brightness_move": 0}'

      ###################################################
      # GROUP 4
      ###################################################
      - conditions: "{{ action == 'group_4_on_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"brightness_move": 50}'

      - conditions: "{{ action == 'group_4_off_hold' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"brightness_move": -50}'

      - conditions: "{{ action in ['group_4_on_release','group_4_off_release'] }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"brightness_move": 0}'
