blueprint:
  name: AwoX 33952 - Spécial Yeelight (V7)
  description: "V7 : Force le changement de température par calcul (Fix Yeelight) et gère l'effet Slowdown."
  domain: automation

  input:
    action_sensor:
      name: Capteur Action (Z2M)
      selector:
        entity:
          domain: sensor
          multiple: false

    target_light:
      name: Lampe Yeelight
      selector:
        entity:
          domain: light

    # --- Actions Cœurs ---
    heart_1_action:
      name: Action Cœur 1 (Haut)
      default: []
      selector:
        action: {}

    heart_2_action:
      name: Action Cœur 2 (Bas)
      default: []
      selector:
        action: {}

    # --- Réglages ---
    step_pct:
      name: Pas de Luminosité (%)
      default: 15
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"
          mode: slider

    kelvin_step:
      name: Pas de Température (Mireds)
      description: "Force du changement chaud/froid."
      default: 50
      selector:
        number:
          min: 10
          max: 150
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to:
      - "unavailable"
      - "unknown"
      - "None"
      - ""

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
      light_entity: !input target_light
      step_p: !input step_pct
      step_k: !input kelvin_step
      
      # --- CALCULS LUMINOSITÉ ---
      step_up: "{{ step_p | int }}"
      step_down: "{{ -1 * step_p | int }}"
      
      # --- CALCULS TEMPÉRATURE (Spécial Yeelight) ---
      # On récupère la valeur actuelle. Si absente (mode couleur), on prend 370 (Blanc Neutre/Chaud)
      current_mireds: "{{ state_attr(light_entity, 'color_temp') | int(default=370) }}"
      
      # Bornes des Yeelights (souvent 153 à 588)
      min_mireds: 153
      max_mireds: 500

      # Calcul de la prochaine valeur (Bornée entre min et max)
      # Plus Chaud (Warm) = Mireds Augmentent
      next_warm: "{{ [ (current_mireds + step_k), max_mireds ] | min }}"
      # Plus Froid (Cold) = Mireds Diminuent
      next_cold: "{{ [ (current_mireds - step_k), min_mireds ] | max }}"

  - choose:
      # =========================================
      # 1. I/O (ON / OFF)
      # =========================================
      - conditions: "{{ action == 'on' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }

      - conditions: "{{ action == 'off' }}"
        sequence:
          - service: light.turn_off
            target: { entity_id: !input target_light }

      # =========================================
      # 2. LUMINOSITÉ
      # =========================================
      - conditions: "{{ action == 'brightness_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { brightness_step_pct: "{{ step_up }}", transition: 0.2 }

      - conditions: "{{ action == 'brightness_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { brightness_step_pct: "{{ step_down }}", transition: 0.2 }

      # =========================================
      # 3. TEMPÉRATURE (Méthode Absolue)
      # =========================================
      
      # Bouton HAUT (Soleil/Etoile) -> Vers le FROID (Moins de Mireds)
      - conditions: "{{ action == 'color_temperature_step_up' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { color_temp: "{{ next_cold }}", transition: 0.2 }

      # Bouton BAS (Flocon/Soleil) -> Vers le CHAUD (Plus de Mireds)
      - conditions: "{{ action == 'color_temperature_step_down' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { color_temp: "{{ next_warm }}", transition: 0.2 }

      # =========================================
      # 4. MODES
      # =========================================
      # REFRESH -> Reset Blanc Neutre
      - conditions: "{{ action == 'refresh' }}" 
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { kelvin: 4000, brightness_pct: 100, effect: "None" }

      # LIGHT MOVEMENT -> SLOWDOWN
      - conditions: "{{ action == 'light_movement' }}"
        sequence:
           - choose:
              - conditions: "{{ state_attr(light_entity, 'effect') == 'slowdown' }}"
                sequence:
                  - service: light.turn_on
                    target: { entity_id: !input target_light }
                    data: { effect: "stop" }
              - conditions: "{{ state_attr(light_entity, 'effect') != 'slowdown' }}"
                sequence:
                  - service: light.turn_on
                    target: { entity_id: !input target_light }
                    data: { effect: "slowdown", brightness_pct: 100 }

      # =========================================
      # 5. COULEURS
      # =========================================
      - conditions: "{{ action == 'red' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [255, 0, 0], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'green' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [0, 255, 0], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'blue' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [0, 0, 255], brightness_pct: 100, effect: "stop" }

      - conditions: "{{ action == 'yellow' }}"
        sequence:
          - service: light.turn_on
            target: { entity_id: !input target_light }
            data: { rgb_color: [255, 220, 0], brightness_pct: 100, effect: "stop" }

      # =========================================
      # 6. FAVORIS (Cœurs)
      # =========================================
      - conditions: "{{ action in ['recall_1', 'store_1', 'scene_1'] }}"
        sequence: !input heart_1_action

      - conditions: "{{ action in ['recall_2', 'store_2', 'scene_2'] }}"
        sequence: !input heart_2_action