blueprint:
  name: Sunricher ZGRC-KEY-013 (Selecteur Liste V3)
  description: Controle 4 groupes de lumieres via Zigbee2MQTT
  domain: automation

  input:
    action_sensor:
      name: Capteur Action
      description: Selectionnez le sensor action
      selector:
        entity:
          domain: sensor
          integration: mqtt
          multiple: false

    light_g1:
      name: Light group 1
      selector:
        entity:
          domain: light
    light_g2:
      name: Light group 2
      selector:
        entity:
          domain: light
    light_g3:
      name: Light group 3
      selector:
        entity:
          domain: light
    light_g4:
      name: Light group 4
      selector:
        entity:
          domain: light

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    not_to: 
      - ""
      - "None"
      - "unavailable"
      - "unknown"

action:
  - variables:
      command: "{{ trigger.to_state.state }}"

  - choose:
      # GROUP 1
      - conditions: "{{ command == 'on_1' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g1
      - conditions: "{{ command == 'off_1' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_g1
      - conditions: "{{ command == 'brightness_move_up_1' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g1
            data:
              brightness_step: 15
      - conditions: "{{ command == 'brightness_move_down_1' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g1
            data:
              brightness_step: -15

      # GROUP 2
      - conditions: "{{ command == 'on_2' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g2
      - conditions: "{{ command == 'off_2' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_g2
      - conditions: "{{ command == 'brightness_move_up_2' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g2
            data:
              brightness_step: 15
      - conditions: "{{ command == 'brightness_move_down_2' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g2
            data:
              brightness_step: -15

      # GROUP 3
      - conditions: "{{ command == 'on_3' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g3
      - conditions: "{{ command == 'off_3' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_g3
      - conditions: "{{ command == 'brightness_move_up_3' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g3
            data:
              brightness_step: 15
      - conditions: "{{ command == 'brightness_move_down_3' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g3
            data:
              brightness_step: -15

      # GROUP 4
      - conditions: "{{ command == 'on_4' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g4
      - conditions: "{{ command == 'off_4' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_g4
      - conditions: "{{ command == 'brightness_move_up_4' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g4
            data:
              brightness_step: 15
      - conditions: "{{ command == 'brightness_move_down_4' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_g4
            data:
              brightness_step: -15