blueprint:
  name: Sunricher ZGRC-KEY-013 Zigbee2MQTT ULTIMATE (brightness_move_up_X)
  domain: automation

  input:
    remote_name:
      name: Friendly name remote
      selector:
        text:

    group1:
      name: Z2M group name 1
      selector:
        text:
    group2:
      name: Z2M group name 2
      selector:
        text:
    group3:
      name: Z2M group name 3
      selector:
        text:
    group4:
      name: Z2M group name 4
      selector:
        text:

mode: parallel
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action

variables:
  remote: !input remote_name
  topic: "{{ trigger.topic }}"
  action: "{{ trigger.payload }}"
  g1: !input group1
  g2: !input group2
  g3: !input group3
  g4: !input group4

condition:
  - "{{ topic == 'zigbee2mqtt/' ~ remote ~ '/action' }}"

action:
  - choose:

      ################################################
      # GROUP 1
      ################################################
      - conditions: "{{ action == 'on_1' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"state":"ON"}'

      - conditions: "{{ action == 'off_1' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"state":"OFF"}'

      - conditions: "{{ action == 'brightness_move_up_1' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"brightness_move": 80}'

      - conditions: "{{ action == 'brightness_move_down_1' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"brightness_move": -80}'

      - conditions: "{{ action == 'brightness_stop_1' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g1 }}/set"
              payload: '{"brightness_move": 0}'

      ################################################
      # GROUP 2
      ################################################
      - conditions: "{{ action == 'on_2' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"state":"ON"}'

      - conditions: "{{ action == 'off_2' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"state":"OFF"}'

      - conditions: "{{ action == 'brightness_move_up_2' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"brightness_move": 80}'

      - conditions: "{{ action == 'brightness_move_down_2' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"brightness_move": -80}'

      - conditions: "{{ action == 'brightness_stop_2' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g2 }}/set"
              payload: '{"brightness_move": 0}'

      ################################################
      # GROUP 3
      ################################################
      - conditions: "{{ action == 'on_3' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"state":"ON"}'

      - conditions: "{{ action == 'off_3' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"state":"OFF"}'

      - conditions: "{{ action == 'brightness_move_up_3' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"brightness_move": 80}'

      - conditions: "{{ action == 'brightness_move_down_3' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"brightness_move": -80}'

      - conditions: "{{ action == 'brightness_stop_3' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g3 }}/set"
              payload: '{"brightness_move": 0}'

      ################################################
      # GROUP 4
      ################################################
      - conditions: "{{ action == 'on_4' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"state":"ON"}'

      - conditions: "{{ action == 'off_4' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"state":"OFF"}'

      - conditions: "{{ action == 'brightness_move_up_4' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"brightness_move": 80}'

      - conditions: "{{ action == 'brightness_move_down_4' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"brightness_move": -80}'

      - conditions: "{{ action == 'brightness_stop_4' }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "zigbee2mqtt/{{ g4 }}/set"
              payload: '{"brightness_move": 0}'
